# Generated by Django 2.1.3 on 2018-12-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_time', models.DateField(auto_now_add=True)),
                ('main_img', models.FileField(upload_to='')),
                ('main_text', models.TextField()),
                ('cate', models.CharField(max_length=30)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='detail',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
