# Generated by Django 2.1.3 on 2018-12-21 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='url_pat',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
