# Generated by Django 2.1.3 on 2018-12-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_url_pat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video',
        ),
    ]
